# build
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
collections:
  assignments:
    output: true
  labs:
    output: true
# theme
noita:
  name: CS68SI
  description: Gitting Ahead With Git
  lang: en
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: Course Description
        url: /about/
      - name: Course Policies
        url: /policies/
      - name: Assignments
        url: /assignments/
      - name: Guides
        url: /guides/
      - name: Repository
        url: https://github.com/cs68si/cs68si.github.io
        class: small button
